CREATE TABLE products (
  id SERIAL PRIMARY KEY,
  nombre VARCHAR(255) NOT NULL,
  categoria VARCHAR(50) NOT NULL,
  descripcion TEXT,
  precio NUMERIC(10,2) NOT NULL,
  imagen_url TEXT,
  stock INT DEFAULT 0,
  activo BOOLEAN DEFAULT TRUE
);

CREATE TABLE home_products (
  id SERIAL PRIMARY KEY,
  product_id INT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  orden INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  UNIQUE (product_id)
);

CREATE TABLE home_carousel (
  id SERIAL PRIMARY KEY,
  imagen_url TEXT NOT NULL,
  orden INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  titulo VARCHAR(50),
  activo BOOLEAN NOT NULL DEFAULT TRUE
);